name = "danger_plugin_pr_hygiene"
version = "0.5.0"
description = "A Danger plugin for enforcing good PR hygiene."
licenses = ["MIT"]
repository = { type = "github", user = "maxdeviant", repo = "danger-plugin-py-hygiene" }

target = "javascript"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 1.0.0"

[dev-dependencies]
startest = ">= 0.5.0 and < 1.0.0"
