name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm format --check
      - run: pnpm build
      - run: pnpm test
