name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: erlef/setup-beam@v1.18.1
        with:
          otp-version: '26.0.2'
          gleam-version: '1.4.1'
          rebar3-version: '3'

      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm format --check
      - run: pnpm build
