name: Danger

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm build

      - name: Run Danger
        run: pnpm danger ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
